import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  Locale _currentLocale = const Locale('en');

  Locale get currentLocale => _currentLocale;

  LanguageService() {
    _loadLanguage();
  }

  Map<String, String> get localizedStrings => _localizedValues[_currentLocale.languageCode] ?? _localizedValues['en']!;

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Ekadashi Calendar',
      'home': 'Home',
      'calendar': 'Calendar',
      'settings': 'Settings',
      'start_fasting': 'Start Fasting',
      'break_fasting': 'Break Fasting',
      'view_details': 'View Details',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'passed': 'Passed',
      'in_days': 'in {} days',
      'locating': 'Locating...',
      'detecting_location': 'Detecting Location...',
      'location_denied': 'Location Denied',
      'failed_load': 'Failed to load data',
      'no_ekadashi': 'No Ekadashi on this day',
      'significance': 'Significance',
      'story_history': 'Story and History',
      'fasting_rules': 'Fasting Rules',
      'spiritual_benefits': 'Spiritual Benefits',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'reminders_active': '{}/4 active',
      'notify_2day': '2 Days Before',
      'notify_1day': '1 Day Before',
      'notify_start': 'Start Fasting',
      'notify_parana': 'Break Fasting',
      'status_active': 'Active',
      'status_disabled': 'Disabled',
      'test_notification': 'Test Notification',
      'test_notification_desc': 'Send a test notification',
      'test_notif_title': '🙏 Hari Om!',
      'test_notif_body': 'Your test notification works!',
      'notifications_off': 'Notifications disabled',
      'permissions': 'Permissions',
      'permissions_ok': 'All set',
      'permissions_needed': 'Action needed',
      'alarms_reminders': 'Alarms',
      'alarms_enabled': 'Enabled',
      'alarms_disabled': 'Disabled',
      'battery_optimization': 'Battery',
      'battery_desc': 'Open App Settings',
      'open_settings': 'Open',
      'settings_button': 'Settings',
      'about': 'About',
      'version': 'Version',
      'rate_app': 'Rate App',
      'rate_app_desc': 'Rate us on Play Store',
      'notif_test_title': '🙏 Hari Om!',
      'notif_test_body': 'Your test notification works!',
      'notif_2day_title': 'Upcoming Ekadashi',
      'notif_2day_body': 'is in 2 days. Prepare for your fast.',
      'notif_1day_title': 'Ekadashi Tomorrow!',
      'notif_1day_body': 'is tomorrow. Fasting starts at',
      'notif_start_title': 'Ekadashi Starts Now',
      'notif_start_body': 'Today is',
      'notif_start_suffix': 'Fasting begins now.',
      'notif_parana_title': 'Parana Time',
      'notif_parana_body': '- You can break your fast now.',
      'notif_sent_msg': 'Notification sent!',
      // Info dialog translations
      'info_close': 'Got it',
      'alarms_info_title': 'Alarms & Reminders',
      'alarms_info_why': 'Why it\'s needed',
      'alarms_info_why_desc': 'Ekadashi fasting times are based on specific sunrise times. Exact alarms ensure you receive reminders at the precise moment.',
      'alarms_info_steps': 'How to enable',
      'alarms_info_step1': '1. Tap "Open" to go to settings',
      'alarms_info_step2': '2. Toggle "Allow setting alarms" ON',
      'alarms_info_note': 'Note: On some devices, this may already be enabled and cannot be changed.',
      'battery_info_title': 'Battery Optimization',
      'battery_info_why': 'Why it\'s needed',
      'battery_info_why_desc': 'If battery optimization is enabled, Android may delay or skip your Ekadashi reminders to save power.',
      'battery_info_steps': 'How to allow background usage',
      'battery_info_step1': '1. Tap "Open" to go to App Info',
      'battery_info_step2': '2. Tap "Battery" or "App battery usage"',
      'battery_info_step3': '3. Enable "Allow background usage" or select "Unrestricted"',
      'battery_info_note': 'This ensures notifications are delivered on time, even when your phone is idle.',
      // Share translations
      'share_app': 'Share App',
      'share_app_desc': 'Tell friends about this app',
      'share_message': '🙏 Ekadashi Calendar - Never miss an Ekadashi!\n\nGet reminders for fasting times, read stories & significance of each Ekadashi.\n\nDownload now: https://play.google.com/store/apps/details?id=com.applausestudios.ekadashi_calendar',
      // City selection translations (NEW)
      'select_city': 'Select City',
      'search_city': 'Search city...',
      'auto_detect_location': 'Auto-detect Location',
      'auto_detect_desc': 'Use GPS to find your city',
      'using_auto_location': 'Using auto-detected location',
      'disable_auto_manual': 'Turn off auto-detect to select a city manually',
      'save': 'Save',
      'location': 'Location',
      'change_city': 'Change City',
      // Location permission dialog
      'location_permission_title': 'Location Required',
      'location_permission_permanent': 'Location permission is permanently disabled. Please enable it in App Settings to use location-based features.',
      'cancel': 'Cancel',
      // App Settings (NEW)
      'app_settings': 'App Settings',
      'app_settings_desc': 'Manage permissions & battery',
      'perm_guide_title': 'Permissions Guide',
      'perm_guide_desc': 'For accurate notifications and location features, please allow:\n• Notifications\n• Location\n• Battery (Unrestricted/Background)',
      // Vrat Tracker & Achievements (Module 04)
      'vrat': 'Vrat',
      'journey': 'Vrat',
      'overview': 'Overview',
      'vrat_tracker': 'Vrat Tracker',
      'vrat_tracker_desc': 'Keep a private record of your Ekadashi observance.',
      'enable_vrat_tracker': 'Enable Vrat Tracker',
      'disable_vrat_tracker': 'Disable Vrat Tracker',
      'tracker_enabled_msg': 'Vrat Tracker enabled. You can now record your observance.',
      'tracker_disabled_msg': 'Vrat Tracker disabled. Your existing history remains saved.',
      'observed': 'Observed',
      'partial': 'Partial',
      'missed': 'Missed',
      'unrecorded': 'Unrecorded',
      'not_recorded': 'Not Recorded',
      'tap_to_record_instruction': 'Tap an Ekadashi to record your observance',
      'tap_to_record_semantics': 'Tap to record Vrat',
      'record_vrat': 'Record Vrat',
      'view_vrat_status': 'View Vrat Status',
      'record_observance': 'Record Observance',
      'edit_record': 'Edit Record',
      'delete_record': 'Delete Record',
      'current_streak': 'Current Streak',
      'longest_streak': 'Longest Streak',
      'annual_completion': 'Annual Completion',
      'total_observed': 'Total Observed',
      'total_partial': 'Total Partial',
      'total_missed': 'Total Missed',
      'fasting_method': 'Fasting Method',
      'method_full_fast': 'Full Fast',
      'method_water_only': 'Water Only',
      'method_fruits_milk': 'Fruits / Milk',
      'method_one_meal': 'One Meal',
      'method_other': 'Other',
      'method_other_hint': 'Enter fasting method',
      'notes': 'Personal Notes',
      'notes_hint': 'Add an optional personal note...',
      'history': 'History',
      'statistics': 'Statistics',
      'achievements': 'Achievements',
      'achievement_unlocked': 'Achievement Unlocked',
      'next_milestone': 'Next Milestone',
      'locked': 'Locked',
      'unlocked': 'Unlocked',
      'ekadashis_unit': 'Ekadashis',
      'filter_all': 'All',
      'year': 'Year',
      'cannot_record_future': 'Future Ekadashis cannot be marked as Observed in advance.',
      'delete_confirm': 'Delete this observance record?',
      'delete_confirm_desc': 'This will remove your record from history. Original calendar data will remain untouched.',
      'achievement_first_vrat_title': 'First Vrat',
      'achievement_first_vrat_desc': 'Your first recorded Ekadashi observance.',
      'achievement_5_vrat_title': '5 Ekadashis',
      'achievement_5_vrat_desc': 'Completed 5 qualifying Ekadashi observances.',
      'achievement_10_vrat_title': '10 Ekadashis',
      'achievement_10_vrat_desc': 'Completed 10 qualifying Ekadashi observances.',
      'achievement_12_vrat_title': '12 Ekadashis',
      'achievement_12_vrat_desc': 'Completed 12 qualifying Ekadashi observances.',
      'achievement_consistent_title': 'Consistent Observance',
      'achievement_consistent_desc': 'Observed 3 consecutive Ekadashis with devotion.',
      'achievement_full_year_title': 'Full-Year Observance',
      'achievement_full_year_desc': 'Observed all Ekadashis in a single calendar year.',
    },

    'ta': {
      'app_title': 'ஏகாதசி காலண்டர்',
      'home': 'முகப்பு',
      'calendar': 'நாட்காட்டி',
      'settings': 'அமைப்புகள்',
      'start_fasting': 'விரதம் ஆரம்பம்',
      'break_fasting': 'விரதம் முடித்தல்',
      'view_details': 'விவரங்கள்',
      'today': 'இன்று',
      'tomorrow': 'நாளை',
      'passed': 'முடிந்தது',
      'in_days': '{} நாட்களில்',
      'locating': 'தேடுகிறது...',
      'detecting_location': 'இருப்பிடம் கண்டறிதல்...',
      'location_denied': 'இருப்பிடம் மறுப்பு',
      'failed_load': 'தரவு ஏற்ற இயலவில்லை',
      'no_ekadashi': 'இந்த நாளில் ஏகாதசி இல்லை',
      'significance': 'சிறப்பு',
      'story_history': 'கதை மற்றும் வரலாறு',
      'fasting_rules': 'விரத விதிமுறைகள்',
      'spiritual_benefits': 'ஆன்மீக பலன்கள்',
      'appearance': 'தோற்றம்',
      'dark_mode': 'இருண்ட பயன்முறை',
      'notifications': 'அறிவிப்புகள்',
      'enable_notifications': 'அறிவிப்புகளை இயக்கு',
      'reminders_active': '{}/4 செயலில்',
      'notify_2day': '2 நாள் முன்',
      'notify_1day': '1 நாள் முன்',
      'notify_start': 'விரதத் தொடக்கம்',
      'notify_parana': 'விரத முடிவு',
      'status_active': 'செயலில்',
      'status_disabled': 'முடக்கம்',
      'test_notification': 'சோதனை அறிவிப்பு',
      'test_notification_desc': 'சோதனை அனுப்பு',
      'test_notif_title': '🙏 அடியேன்',
      'test_notif_body': 'உங்கள் சோதனை அறிவிப்பு வேலை செய்கிறது!',
      'notifications_off': 'அறிவிப்புகள் முடக்கம்',
      'permissions': 'அனுமதிகள்',
      'permissions_ok': 'சரி',
      'permissions_needed': 'செயல் தேவை',
      'alarms_reminders': 'அலாரம்',
      'alarms_enabled': 'இயக்கம்',
      'alarms_disabled': 'முடக்கம்',
      'battery_optimization': 'பேட்டரி',
      'battery_desc': 'ஆப் அமைப்புகள்',
      'open_settings': 'திற',
      'settings_button': 'அமைப்புகள்',
      'about': 'பற்றி',
      'version': 'பதிப்பு',
      'rate_app': 'எங்களை மதிப்பிடு',
      'rate_app_desc': 'பிளே ஸ்டோரில் எங்களை மதிப்பிடவும்',
      'notif_test_title': '🙏 அடியேன்',
      'notif_test_body': 'உங்கள் சோதனை அறிவிப்பு வேலை செய்கிறது!',
      'notif_2day_title': 'வரவிருக்கும் ஏகாதசி',
      'notif_2day_body': '2 நாட்களில் வருகிறது. தயாராகுங்கள்.',
      'notif_1day_title': 'நாளை ஏகாதசி!',
      'notif_1day_body': 'நாளை. விரதம் தொடங்கும் நேரம்:',
      'notif_start_title': 'ஏகாதசி தொடங்குகிறது',
      'notif_start_body': 'இன்று',
      'notif_start_suffix': 'விரதம் இப்போது தொடங்குகிறது.',
      'notif_parana_title': 'பாரணை நேரம்',
      'notif_parana_body': '- இப்போது விரதத்தை முடிக்கலாம்.',
      'notif_sent_msg': 'அறிவிப்பு அனுப்பப்பட்டது!',
      // Info dialog translations
      'info_close': 'சரி',
      'alarms_info_title': 'அலாரம் & நினைவூட்டல்',
      'alarms_info_why': 'ஏன் தேவை',
      'alarms_info_why_desc': 'ஏகாதசி விரத நேரங்கள் குறிப்பிட்ட சூரிய உதய நேரத்தை அடிப்படையாகக் கொண்டவை. சரியான நேரத்தில் நினைவூட்டல்கள் பெற இது உதவுகிறது.',
      'alarms_info_steps': 'இயக்குவது எப்படி',
      'alarms_info_step1': '1. அமைப்புகளுக்கு "திற" தட்டவும்',
      'alarms_info_step2': '2. "அலாரம் அமைக்க அனுமதி" ON செய்யவும்',
      'alarms_info_note': 'குறிப்பு: சில சாதனங்களில், இது ஏற்கனவே இயக்கப்பட்டிருக்கும்.',
      'battery_info_title': 'பேட்டரி உகப்பாக்கம்',
      'battery_info_why': 'ஏன் தேவை',
      'battery_info_why_desc': 'பேட்டரி உகப்பாக்கம் இயக்கப்பட்டிருந்தால், உங்கள் ஏகாதசி நினைவூட்டல்கள் தாமதமாகலாம் அல்லது தவறவிடப்படலாம்.',
      'battery_info_steps': 'பின்னணி பயன்பாட்டை அனுமதிப்பது எப்படி',
      'battery_info_step1': '1. ஆப் தகவலுக்கு "திற" தட்டவும்',
      'battery_info_step2': '2. "பேட்டரி" தட்டவும்',
      'battery_info_step3': '3. "பின்னணி பயன்பாட்டை அனுமதி" இயக்கவும் அல்லது "வரம்பற்றது" தேர்வு செய்யவும்',
      'battery_info_note': 'இது உங்கள் தொலைபேசி செயலற்ற நிலையிலும் அறிவிப்புகள் சரியான நேரத்தில் வருவதை உறுதி செய்கிறது.',
      // Share translations
      'share_app': 'ஆப்பை பகிர்',
      'share_app_desc': 'நண்பர்களிடம் பகிரவும்',
      'share_message': '🙏 ஏகாதசி காலண்டர் - ஒரு ஏகாதசியையும் தவறவிடாதீர்கள்!\n\nவிரத நேர நினைவூட்டல்கள், ஒவ்வொரு ஏகாதசியின் கதைகள் & முக்கியத்துவம் பெறுங்கள்.\n\nஇப்போது பதிவிறக்கவும்: https://play.google.com/store/apps/details?id=com.applausestudios.ekadashi_calendar',
      // City selection translations (NEW)
      'select_city': 'நகரத்தை தேர்வு செய்',
      'search_city': 'நகரத்தை தேடு...',
      'auto_detect_location': 'தானியங்கி இருப்பிட கண்டறிதல்',
      'auto_detect_desc': 'உங்கள் நகரத்தை கண்டறிய GPS பயன்படுத்தவும்',
      'using_auto_location': 'தானியங்கி இருப்பிடம் பயன்படுத்துகிறது',
      'disable_auto_manual': 'கைமுறையாக தேர்வு செய்ய தானியங்கியை அணைக்கவும்',
      'save': 'சேமி',
      'location': 'இருப்பிடம்',
      'change_city': 'நகரத்தை மாற்று',
      // Location permission dialog
      'location_permission_title': 'இருப்பிடம் தேவை',
      'location_permission_permanent': 'இருப்பிட அனுமதி நிரந்தரமாக முடக்கப்பட்டுள்ளது. இருப்பிட அம்சங்களைப் பயன்படுத்த ஆப் அமைப்புகளில் இயக்கவும்.',
      'cancel': 'ரத்து செய்',
      // App Settings (NEW)
      'app_settings': 'ஆப் அமைப்புகள்',
      'app_settings_desc': 'அனுமதிகள் மற்றும் பேட்டரியை நிர்வகிக்கவும்',
      'perm_guide_title': 'அனுமதி வழிகாட்டி',
      'perm_guide_desc': 'துல்லியமான அறிவிப்புகள் மற்றும் இருப்பிட அம்சங்களுக்கு, அனுமதிக்கவும்:\n• அறிவிப்புகள்\n• இருப்பிடம்\n• பேட்டரி (வரம்பற்ற/பின்னணி)',
      // Vrat Tracker & Achievements (Module 04)
      'vrat': 'விரதம்',
      'journey': 'விரதம்',
      'overview': 'கண்ணோட்டம்',
      'vrat_tracker': 'விரத கண்காணிப்பு',
      'vrat_tracker_desc': 'உங்கள் ஏகாதசி விரத அனுஷ்டானங்களை தனிப்பட்ட முறையில் பதிவு செய்யுங்கள்.',
      'enable_vrat_tracker': 'விரத கண்காணிப்பை இயக்கு',
      'disable_vrat_tracker': 'விரத கண்காணிப்பை முடக்கு',
      'tracker_enabled_msg': 'விரத கண்காணிப்பு இயக்கப்பட்டது. உங்கள் விரதத்தைப் பதிவு செய்யலாம்.',
      'tracker_disabled_msg': 'விரத கண்காணிப்பு முடக்கப்பட்டது. உங்கள் முந்தைய பதிவுகள் பாதுகாப்பாக இருக்கும்.',
      'observed': 'அனுஷ்டிக்கப்பட்டது',
      'partial': 'பகுதி விரதம்',
      'missed': 'தவறவிடப்பட்டது',
      'unrecorded': 'பதிவு செய்யப்படவில்லை',
      'not_recorded': 'பதிவு செய்யப்படவில்லை',
      'tap_to_record_instruction': 'விரதப் பதிவைச் சேர்க்க ஏகாதசியைத் தட்டவும்',
      'tap_to_record_semantics': 'விரதம் பதிவு செய்ய தட்டவும்',
      'record_vrat': 'விரதம் பதிவு செய்',
      'view_vrat_status': 'விரத நிலை',
      'record_observance': 'விரதத்தை பதிவு செய்',
      'edit_record': 'பதிவை திருத்து',
      'delete_record': 'பதிவை நீக்கு',
      'current_streak': 'தற்போதைய தொடர்',
      'longest_streak': 'நீண்ட தொடர்',
      'annual_completion': 'ஆண்டு நிறைவு',
      'total_observed': 'மொத்த அனுஷ்டானங்கள்',
      'total_partial': 'மொத்த பகுதி விரதங்கள்',
      'total_missed': 'மொத்த தவறவிட்டவை',
      'fasting_method': 'விரத முறை',
      'method_full_fast': 'முழு விரதம்',
      'method_water_only': 'நீர் மட்டும்',
      'method_fruits_milk': 'பழம் / பால்',
      'method_one_meal': 'ஒரு வேளை உணவு',
      'method_other': 'பிற',
      'method_other_hint': 'விரத முறையை உள்ளிடவும்',
      'notes': 'தனிப்பட்ட குறிப்புகள்',
      'notes_hint': 'விருப்பப்பட்டால் குறிப்பை சேர்க்கவும்...',
      'history': 'வரலாறு',
      'statistics': 'புள்ளிவிவரங்கள்',
      'achievements': 'மைல்கற்கள்',
      'achievement_unlocked': 'மைல்கல் எட்டப்பட்டது',
      'next_milestone': 'அடுத்த மைல்கல்',
      'locked': 'பூட்டப்பட்டது',
      'unlocked': 'திறக்கப்பட்டது',
      'ekadashis_unit': 'ஏகாதசிகள்',
      'filter_all': 'அனைத்தும்',
      'year': 'ஆண்டு',
      'cannot_record_future': 'எதிர்கால ஏகாதசியை முன்கூட்டியே அனுஷ்டித்ததாகக் குறிக்க இயலாது.',
      'delete_confirm': 'இந்த விரதப் பதிவை நீக்கவா?',
      'delete_confirm_desc': 'இது வரலாற்றிலிருந்து மட்டுமே நீக்கப்படும். காலண்டர் தரவு மாறாது.',
      'achievement_first_vrat_title': 'முதல் விரதம்',
      'achievement_first_vrat_desc': 'உங்கள் முதல் ஏகாதசி விரத அனுஷ்டானம்.',
      'achievement_5_vrat_title': '5 ஏகாதசிகள்',
      'achievement_5_vrat_desc': '5 ஏகாதசி விரதங்களை நிறைவு செய்துள்ளீர்கள்.',
      'achievement_10_vrat_title': '10 ஏகாதசிகள்',
      'achievement_10_vrat_desc': '10 ஏகாதசி விரதங்களை நிறைவு செய்துள்ளீர்கள்.',
      'achievement_12_vrat_title': '12 ஏகாதசிகள்',
      'achievement_12_vrat_desc': '12 ஏகாதசி விரதங்களை நிறைவு செய்துள்ளீர்கள்.',
      'achievement_consistent_title': 'தொடர்ச்சியான விரதம்',
      'achievement_consistent_desc': 'தொடர்ந்து 3 ஏகாதசிகள் பக்தியுடன் அனுஷ்டிக்கப்பட்டது.',
      'achievement_full_year_title': 'முழு ஆண்டு விரதம்',
      'achievement_full_year_desc': 'ஒரு முழு ஆண்டின் அனைத்து ஏகாதசிகளையும் அனுஷ்டித்தீர்கள்.',
    },

    'hi': {
      'app_title': 'एकादशी कैलेंडर',
      'home': 'होम',
      'calendar': 'कैलेंडर',
      'settings': 'सेटिंग्स',
      'start_fasting': 'व्रत प्रारंभ',
      'break_fasting': 'व्रत पारण',
      'view_details': 'विवरण देखें',
      'today': 'आज',
      'tomorrow': 'कल',
      'passed': 'बीत गया',
      'in_days': '{} दिनों में',
      'locating': 'खोज रहा है...',
      'detecting_location': 'स्थान पता लगा रहा है...',
      'location_denied': 'स्थान अस्वीकृत',
      'failed_load': 'डेटा लोड विफल',
      'no_ekadashi': 'इस दिन एकादशी नहीं है',
      'significance': 'महत्व',
      'story_history': 'कथा और इतिहास',
      'fasting_rules': 'व्रत के नियम',
      'spiritual_benefits': 'आध्यात्मिक लाभ',
      'appearance': 'दिखावट',
      'dark_mode': 'डार्क मोड',
      'notifications': 'सूचनाएं',
      'enable_notifications': 'सूचनाएं सक्षम करें',
      'reminders_active': '{}/4 सक्रिय',
      'notify_2day': '2 दिन पहले',
      'notify_1day': '1 दिन पहले',
      'notify_start': 'व्रत आरंभ',
      'notify_parana': 'व्रत समाप्ति',
      'status_active': 'सक्रिय',
      'status_disabled': 'अक्षम',
      'test_notification': 'टेस्ट नोटिफिकेशन',
      'test_notification_desc': 'टेस्ट भेजें',
      'test_notif_title': '🙏 हरि ॐ!',
      'test_notif_body': 'आपकी टेस्ट नोटिफिकेशन काम कर रही है!',
      'notifications_off': 'सूचनाएं बंद',
      'permissions': 'अनुमतियां',
      'permissions_ok': 'सब ठीक',
      'permissions_needed': 'कार्रवाई जरूरी',
      'alarms_reminders': 'अलार्म',
      'alarms_enabled': 'सक्षम',
      'alarms_disabled': 'अक्षम',
      'battery_optimization': 'बैटरी',
      'battery_desc': 'ऐप सेटिंग्स',
      'open_settings': 'खोलें',
      'settings_button': 'सेटिंग्स',
      'about': 'बारे में',
      'version': 'संस्करण',
      'rate_app': 'ऐप रेट करें',
      'rate_app_desc': 'प्ले स्टोर पर हमें रेट करें',
      'notif_test_title': '🙏 हरि ॐ!',
      'notif_test_body': 'आपकी टेस्ट नोटिफिकेशन काम कर रही है!',
      'notif_2day_title': 'आगामी एकादशी',
      'notif_2day_body': '2 दिनों में है। तैयारी करें।',
      'notif_1day_title': 'कल एकादशी!',
      'notif_1day_body': 'कल है। व्रत शुरू:',
      'notif_start_title': 'एकादशी अब शुरू',
      'notif_start_body': 'आज है',
      'notif_start_suffix': 'व्रत अब शुरू।',
      'notif_parana_title': 'पारण का समय',
      'notif_parana_body': '- अब व्रत तोड़ सकते हैं।',
      'notif_sent_msg': 'नोटिफिकेशन भेजा गया!',
      // Info dialog translations
      'info_close': 'समझ गया',
      'alarms_info_title': 'अलार्म और रिमाइंडर',
      'alarms_info_why': 'यह क्यों जरूरी है',
      'alarms_info_why_desc': 'एकादशी व्रत का समय विशेष सूर्योदय समय पर आधारित होता है। सटीक अलार्म सुनिश्चित करता है कि आपको सही समय पर रिमाइंडर मिले।',
      'alarms_info_steps': 'कैसे सक्षम करें',
      'alarms_info_step1': '1. सेटिंग्स पर जाने के लिए "खोलें" टैप करें',
      'alarms_info_step2': '2. "अलार्म सेट करने की अनुमति" ON करें',
      'alarms_info_note': 'नोट: कुछ डिवाइस पर, यह पहले से सक्षम हो सकता है।',
      'battery_info_title': 'बैटरी ऑप्टिमाइज़ेशन',
      'battery_info_why': 'यह क्यों जरूरी है',
      'battery_info_why_desc': 'अगर बैटरी ऑप्टिमाइज़ेशन सक्षम है, तो Android आपके एकादशी रिमाइंडर में देरी कर सकता है या छोड़ सकता है।',
      'battery_info_steps': 'बैकग्राउंड उपयोग कैसे अनुमति दें',
      'battery_info_step1': '1. ऐप जानकारी के लिए "खोलें" टैप करें',
      'battery_info_step2': '2. "बैटरी" पर टैप करें',
      'battery_info_step3': '3. "बैकग्राउंड उपयोग अनुमति दें" सक्षम करें या "अप्रतिबंधित" चुनें',
      'battery_info_note': 'यह सुनिश्चित करता है कि आपका फोन निष्क्रिय होने पर भी नोटिफिकेशन समय पर आएं।',
      // Share translations
      'share_app': 'ऐप शेयर करें',
      'share_app_desc': 'दोस्तों को बताएं',
      'share_message': '🙏 एकादशी कैलेंडर - कोई एकादशी न छूटे!\n\nव्रत के समय की याद दिलाएं, हर एकादशी की कथाएं और महत्व पढ़ें।\n\nअभी डाउनलोड करें: https://play.google.com/store/apps/details?id=com.applausestudios.ekadashi_calendar',
      // City selection translations (NEW)
      'select_city': 'शहर चुनें',
      'search_city': 'शहर खोजें...',
      'auto_detect_location': 'स्थान स्वतः पता लगाएं',
      'auto_detect_desc': 'अपना शहर खोजने के लिए GPS का उपयोग करें',
      'using_auto_location': 'स्वतः पता लगाया गया स्थान उपयोग कर रहे हैं',
      'disable_auto_manual': 'मैन्युअल रूप से चुनने के लिए स्वतः पता लगाना बंद करें',
      'save': 'सेव करें',
      'location': 'स्थान',
      'change_city': 'शहर बदलें',
      // Location permission dialog
      'location_permission_title': 'स्थान आवश्यक',
      'location_permission_permanent': 'स्थान अनुमति स्थायी रूप से अक्षम है। स्थान-आधारित सुविधाओं का उपयोग करने के लिए कृपया ऐप सेटिंग्स में इसे सक्षम करें।',
      'cancel': 'रद्द करें',
      // App Settings (NEW)
      'app_settings': 'ऐप सेटिंग्स',
      'app_settings_desc': 'अनुमतियां और बैटरी प्रबंधित करें',
      'perm_guide_title': 'अनुमति गाइड',
      'perm_guide_desc': 'सटीक सूचनाओं और स्थान सुविधाओं के लिए, कृपया अनुमति दें:\n• सूचनाएं\n• स्थान\n• बैटरी (अप्रतिबंधित/पृष्ठभूमि)',
      // Vrat Tracker & Achievements (Module 04)
      'vrat': 'व्रत',
      'journey': 'व्रत',
      'overview': 'अवलोकन',
      'vrat_tracker': 'व्रत ट्रैकर',
      'vrat_tracker_desc': 'अपने एकादशी व्रत का निजी रिकॉर्ड रखें।',
      'enable_vrat_tracker': 'व्रत ट्रैकर सक्षम करें',
      'disable_vrat_tracker': 'व्रत ट्रैकर अक्षम करें',
      'tracker_enabled_msg': 'व्रत ट्रैकर सक्षम हुआ। अब आप अपना व्रत दर्ज कर सकते हैं।',
      'tracker_disabled_msg': 'व्रत ट्रैकर अक्षम किया गया। आपका पुराना इतिहास सुरक्षित रहेगा।',
      'observed': 'संपन्न',
      'partial': 'आंशिक व्रत',
      'missed': 'छूट गया',
      'unrecorded': 'अदर्जित',
      'not_recorded': 'अनलिखित',
      'tap_to_record_instruction': 'अपने व्रत का रिकॉर्ड दर्ज करने के लिए एकादशी पर टैप करें',
      'tap_to_record_semantics': 'व्रत दर्ज करने के लिए टैप करें',
      'record_vrat': 'व्रत दर्ज करें',
      'view_vrat_status': 'व्रत स्थिति',
      'record_observance': 'व्रत दर्ज करें',
      'edit_record': 'रिकॉर्ड बदलें',
      'delete_record': 'रिकॉर्ड हटाएं',
      'current_streak': 'वर्तमान लड़ी',
      'longest_streak': 'सर्वश्रेष्ठ लड़ी',
      'annual_completion': 'वार्षिक पूर्णता',
      'total_observed': 'कुल संपन्न',
      'total_partial': 'कुल आंशिक',
      'total_missed': 'कुल छूटे',
      'fasting_method': 'व्रत विधि',
      'method_full_fast': 'पूर्ण उपवास',
      'method_water_only': 'जलाहार',
      'method_fruits_milk': 'फलाहार / दुग्ध',
      'method_one_meal': 'एक समय भोजन',
      'method_other': 'अन्य',
      'method_other_hint': 'व्रत विधि दर्ज करें',
      'notes': 'व्यक्तिगत टिप्पणी',
      'notes_hint': 'वैकल्पिक टिप्पणी लिखें...',
      'history': 'इतिहास',
      'statistics': 'आंकड़े',
      'achievements': 'उपलब्धियां',
      'achievement_unlocked': 'उपलब्धि अनलॉक हुई',
      'next_milestone': 'अगला पड़ाव',
      'locked': 'लॉक्ड',
      'unlocked': 'अनलॉक्ड',
      'ekadashis_unit': 'एकादशियां',
      'filter_all': 'सभी',
      'year': 'वर्ष',
      'cannot_record_future': 'भविष्य की एकादशी को पहले से संपन्न के रूप में दर्ज नहीं किया जा सकता।',
      'delete_confirm': 'क्या आप यह रिकॉर्ड हटाना चाहते हैं?',
      'delete_confirm_desc': 'यह केवल व्रत इतिहास से हटेगा। कैलेंडर डेटा अपरिवर्तित रहेगा।',
      'achievement_first_vrat_title': 'पहला व्रत',
      'achievement_first_vrat_desc': 'आपका पहला दर्ज एकादशी व्रत।',
      'achievement_5_vrat_title': '5 एकादशियां',
      'achievement_5_vrat_desc': '5 एकादशी व्रत सफलतापूर्वक संपन्न किए।',
      'achievement_10_vrat_title': '10 एकादशियां',
      'achievement_10_vrat_desc': '10 एकादशी व्रत सफलतापूर्वक संपन्न किए।',
      'achievement_12_vrat_title': '12 एकादशियां',
      'achievement_12_vrat_desc': '12 एकादशी व्रत सफलतापूर्वक संपन्न किए।',
      'achievement_consistent_title': 'निरंतर निष्ठा',
      'achievement_consistent_desc': 'लगातार 3 एकादशी व्रत भक्तिपूर्वक संपन्न किए।',
      'achievement_full_year_title': 'पूर्ण वर्ष व्रत',
      'achievement_full_year_desc': 'एक पूरे वर्ष की सभी एकादशियों का विधिवत पालन किया।',
    }
  };

  String translate(String key) {
    return _localizedValues[_currentLocale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  String translateWithArgs(String key, List<String> args) {
    String text = translate(key);
    for (var arg in args) {
      text = text.replaceFirst('{}', arg);
    }
    return text;
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final String? languageCode = prefs.getString('language_code');
    if (languageCode != null) {
      _currentLocale = Locale(languageCode);
      notifyListeners();
    }
  }

  Future<void> changeLanguage(String languageCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', languageCode);
    _currentLocale = Locale(languageCode);
    notifyListeners();
  }
}