#!/usr/bin/env python3
"""Generate the compatibility adapter from the ARB schema (no translation calls)."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
data = json.loads((root/'lib/l10n/app_en.arb').read_text())
lines = ["// Generated by tool/generate_localized_lookup.py. Do not edit.",
         "import 'generated/app_localizations.dart';",
         "Map<String, String> localizedLookup(AppLocalizations l) => {"]
for key, value in data.items():
    if key.startswith('@'): continue
    n = len(data.get('@'+key, {}).get('placeholders', {}))
    expr = f'l.{key}' + ('(' + ', '.join("'{}'" for _ in range(n)) + ')' if n else '')
    lines.append(f"  '{key}': {expr},")
lines.append('};')
(root/'lib/l10n/localized_lookup.dart').write_text('\n'.join(lines)+'\n')
