#!/usr/bin/env python3
"""Generate the iOS EkadashiCore resources from the Flutter app's sources.

Usage: python3 tool/ios/generate_core_resources.py

The Flutter app stays the single source of truth; rerun this after changing
any of the inputs below. EkadashiCoreTests/ResourceSyncTests fails when the
copies drift.

- assets/calendar/*.json            -> Resources/calendar/ (byte copies)
- assets/panchang/cities.json, place_names.json -> Resources/panchang/
- lib/services/time_zone_data.dart  -> Resources/tz/tzdb.tzf (the same IANA
  release, decoded from its UTF-16 escapes to the timezone package's binary
  format, so iOS converts local times exactly like Android)
- lib/l10n/app_{en,ta,hi,te,gu,bn}.arb -> Resources/l10n/strings.json
- lib/services/panchang/ephemeris_series.dart, lunar_series.dart
                                    -> Sources/EkadashiCore/Panchang/*Series.swift
"""
import json
import pathlib
import re
import shutil
import struct

ROOT = pathlib.Path(__file__).resolve().parents[2]
CORE = ROOT / "ios-native" / "EkadashiCore" / "Sources" / "EkadashiCore"
RES = CORE / "Resources"
LANGUAGES = ["en", "ta", "hi", "te", "gu", "bn"]


def copy_assets():
    (RES / "calendar").mkdir(parents=True, exist_ok=True)
    for path in sorted((ROOT / "assets" / "calendar").glob("*.json")):
        shutil.copyfile(path, RES / "calendar" / path.name)
    (RES / "panchang").mkdir(parents=True, exist_ok=True)
    for name in ["cities.json", "place_names.json"]:
        shutil.copyfile(ROOT / "assets" / "panchang" / name, RES / "panchang" / name)


def time_zones():
    source = (ROOT / "lib" / "services" / "time_zone_data.dart").read_text()
    release = re.search(r"timeZoneDataRelease = '([^']+)'", source).group(1)
    text = re.search(r"const _embeddedData =\s*'(.*)';", source, re.S).group(1)
    units = [int(h, 16) for h in re.findall(r"\\u([0-9a-f]{4})", text)]
    (RES / "tz").mkdir(parents=True, exist_ok=True)
    (RES / "tz" / "tzdb.tzf").write_bytes(struct.pack("<%dH" % len(units), *units))
    (RES / "tz" / "release.txt").write_text(release + "\n")


def strings():
    table = {}
    for language in LANGUAGES:
        arb = json.loads((ROOT / "lib" / "l10n" / f"app_{language}.arb").read_text())
        table[language] = {k: v for k, v in arb.items() if not k.startswith("@")}
    keys = set(table["en"])
    for language in LANGUAGES:
        missing = keys - set(table[language])
        if missing:
            raise SystemExit(f"{language} is missing {sorted(missing)[:5]}")
    (RES / "l10n").mkdir(parents=True, exist_ok=True)
    (RES / "l10n" / "strings.json").write_text(
        json.dumps(table, ensure_ascii=False, indent=1, sort_keys=True) + "\n")


def dart_rows(text, name):
    """Rows of a `const name = <List<double>>[[...], ...];` declaration."""
    if re.search(rf"const {name} = <List<double>>\[\];", text):
        return []
    body = re.search(rf"const {name} = <List<double>>\[(.*?)\n\];", text, re.S)
    if body is None:
        raise SystemExit(f"{name} not found")
    rows = re.findall(r"\[([^\[\]]*)\]", body.group(1))
    return [[float(v) for v in row.replace("\n", " ").split(",") if v.strip()] for row in rows]


def swift_array(name, rows, width):
    for row in rows:
        assert len(row) == width, (name, row)
    values = [repr(v) for row in rows for v in row]
    lines = [", ".join(values[i:i + width]) for i in range(0, len(values), width)]
    inner = ",\n    ".join(lines)
    return f"    static let {name}: [Double] = [\n    {inner}\n    ]\n" if rows else f"    static let {name}: [Double] = []\n"


def series():
    eph = (ROOT / "lib" / "services" / "panchang" / "ephemeris_series.dart").read_text()
    out = ["// GENERATED by tool/ios/generate_core_resources.py from",
           "// lib/services/panchang/ephemeris_series.dart. Do not edit.",
           "//",
           "// VSOP87D Earth series (Bretagnon & Francou 1988, CDS VI/81), flat",
           "// rows of (amplitude, phase, frequency); IAU 1980 nutation rows of nine.",
           "",
           "enum EphemerisSeries {"]
    for body, count in (("L", 6), ("B", 5), ("R", 6)):
        for k in range(count):
            out.append(swift_array(f"earth{body}{k}", dart_rows(eph, f"earth{body}{k}"), 3))
        names = ", ".join(f"earth{body}{k}" for k in range(count))
        out.append(f"    static let earth{body}: [[Double]] = [{names}]\n")
    out.append(swift_array("nutation1980", dart_rows(eph, "nutation1980"), 9))
    out.append("}\n")
    (CORE / "Panchang" / "EphemerisSeries.swift").write_text("\n".join(out))

    lunar = (ROOT / "lib" / "services" / "panchang" / "lunar_series.dart").read_text()
    mean = re.search(r"const elpMeanLongitude = <double>\[(.*?)\];", lunar, re.S).group(1)
    mean_values = ", ".join(repr(float(v)) for v in mean.split(",") if v.strip())
    scale = re.search(r"const elpDistanceScale = ([^;]+);", lunar).group(1)
    out = ["// GENERATED by tool/ios/generate_core_resources.py from",
           "// lib/services/panchang/lunar_series.dart. Do not edit.",
           "//",
           "// ELP 2000-82B (Chapront-Touze & Chapront, CDS VI/79), flat rows of",
           "// (amplitude, power of T, c0, c1, c2, c3, c4).",
           "",
           "enum LunarSeries {",
           f"    static let meanLongitude: [Double] = [{mean_values}]",
           f"    static let distanceScale: Double = {scale}",
           ""]
    for name, dart in (("longitude", "elpLongitude"), ("latitude", "elpLatitude"), ("distance", "elpDistance")):
        out.append(swift_array(name, dart_rows(lunar, dart), 7))
    out.append("}\n")
    (CORE / "Panchang" / "LunarSeries.swift").write_text("\n".join(out))


def main():
    (CORE / "Panchang").mkdir(parents=True, exist_ok=True)
    copy_assets()
    time_zones()
    strings()
    series()
    print("EkadashiCore resources written to", CORE.relative_to(ROOT))


if __name__ == "__main__":
    main()
