#!/usr/bin/env python3
"""Generate lib/services/panchang/ephemeris_series.dart.

Usage: python generate_series.py VSOP87D.ear nut80.c OUT.dart

Inputs (public, not shipped):
- VSOP87D.ear: Bretagnon & Francou (1988), heliocentric ecliptic of date,
  CDS catalogue VI/81, https://cdsarc.cds.unistra.fr/ftp/VI/81/VSOP87D.ear
- nut80.c: ERFA (BSD-3, derived from IAU SOFA) IAU 1980 nutation table,
  https://github.com/liberfa/erfa/blob/master/src/nut80.c

VSOP terms are truncated so that every omitted term contributes less than
the stated threshold anywhere in 1900-2100 (|tau| <= 0.1 millennia).
"""
import re
import sys

L_THRESHOLD = 2e-8   # radians (about 0.004")
B_THRESHOLD = 2e-8
R_THRESHOLD = 2e-7   # AU; only aberration and light time use R


def read_vsop(path):
    series = {}
    variable = power = None
    for line in open(path):
        if "VSOP87" in line:
            match = re.search(r"VARIABLE (\d).*\*T\*\*(\d)", line)
            variable, power = int(match.group(1)), int(match.group(2))
            series.setdefault(variable, {})[power] = []
            continue
        parts = line.split()
        a, b, c = float(parts[-3]), float(parts[-2]), float(parts[-1])
        series[variable][power].append((a, b, c))
    return series


def truncate(series, threshold):
    result = {}
    for power, terms in series.items():
        scale = 0.1 ** power
        result[power] = [t for t in terms if abs(t[0]) * scale >= threshold]
    return result


def read_nut80(path):
    text = open(path).read()
    body = text[text.index("} x[] = {"):text.index("};", text.index("} x[] = {"))]
    rows = re.findall(r"\{([^{}]+)\}", body)
    table = []
    for row in rows:
        values = [v.strip() for v in row.split(",")]
        table.append([int(v) for v in values[:5]] + [float(v) for v in values[5:]])
    return table


def dart_list(name, terms):
    lines = [f"const {name} = <List<double>>["]
    for a, b, c in terms:
        lines.append(f"  [{a!r}, {b!r}, {c!r}],")
    lines.append("];")
    return "\n".join(lines)


def main():
    vsop = read_vsop(sys.argv[1])
    nut = read_nut80(sys.argv[2])
    names = {1: ("L", L_THRESHOLD), 2: ("B", B_THRESHOLD), 3: ("R", R_THRESHOLD)}
    out = ["// GENERATED by tool/panchang_accuracy/generate_series.py. Do not edit.",
           "//",
           "// VSOP87D Earth (Bretagnon & Francou 1988, CDS VI/81), truncated:",
           f"// L/B terms below {L_THRESHOLD:g} rad and R terms below {R_THRESHOLD:g} AU",
           "// over 1900-2100 are omitted. Rows: amplitude, phase, frequency;",
           "// term = A cos(B + C tau), tau in Julian millennia (TDB) from J2000.",
           "//",
           "// IAU 1980 nutation (ERFA nut80.c, BSD-3-Clause, derived from IAU SOFA).",
           "// Rows: l, l', F, D, Omega multipliers; dpsi sin, t; deps cos, t",
           "// (0.1 milliarcsecond units).",
           ""]
    counts = []
    for variable, (letter, threshold) in names.items():
        truncated = truncate(vsop[variable], threshold)
        parts = []
        for power in sorted(truncated):
            parts.append(f"earth{letter}{power}")
            out.append(dart_list(f"earth{letter}{power}", truncated[power]))
            out.append("")
            counts.append(f"{letter}{power}={len(truncated[power])}")
        out.append(f"const earth{letter} = [{', '.join(parts)}];")
        out.append("")
    out.append("const nutation1980 = <List<double>>[")
    for row in nut:
        out.append("  [" + ", ".join(repr(float(v)) for v in row) + "],")
    out.append("];")
    open(sys.argv[3], "w").write("\n".join(out) + "\n")
    print("terms:", ", ".join(counts), "nutation:", len(nut))


if __name__ == "__main__":
    main()
