#!/usr/bin/env python3
"""Write lib/services/time_zone_data.dart from a timezone-package .tzf file.

Usage: embed.py RELEASE latest_all.tzf OUT.dart
The bytes are stored as UTF-16 code units, the same encoding the timezone
package uses for its bundled data, and loaded through its public
initializeDatabase API.
"""
import struct
import sys

release, source, out = sys.argv[1:4]
data = open(source, "rb").read()
assert len(data) % 2 == 0
units = struct.unpack("<%dH" % (len(data) // 2), data)
text = "".join("\\u%04x" % u for u in units)
open(out, "w").write(f"""// GENERATED by tool/time_zones/update.sh from IANA tzdata {release}
// (https://data.iana.org/time-zones/releases/tzdata{release}.tar.gz,
// signature verified). Do not edit.
import 'dart:typed_data';

import 'package:timezone/timezone.dart' as tz;

/// IANA time zone database release bundled with the app.
const timeZoneDataRelease = '{release}';

/// Loads every IANA location (including historical rules) into
/// package:timezone. Safe to call more than once.
void initializeTimeZoneData() => tz.initializeDatabase(
  Uint16List.fromList(_embeddedData.codeUnits).buffer.asUint8List(),
);

// ignore: unnecessary_string_escapes
const _embeddedData =
    '{text}';
""")
print(out, len(data), "bytes")
